package final_project;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Test extends JPanel {
    private JCheckBox hash_Browns;
    private JCheckBox pancake;
    private JButton calculate_Total;
    private JTextArea pancake_user;
    private JTextArea hashBrown_user;

    public Test() {
        //construct components
        hash_Browns = new JCheckBox ("Hash Browns");
        pancake = new JCheckBox ("Pancake");
        calculate_Total = new JButton ("Calculate Total");
        pancake_user = new JTextArea (5, 5);
        hashBrown_user = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (752, 430));
        setLayout (null);

        //add components
        add (hash_Browns);
        add (pancake);
        add (calculate_Total);
        add (pancake_user);
        add (hashBrown_user);
        calculate_Total.addActionListener(new CalcButtonListener());

        //set component bounds (only needed by Absolute Positioning)
        hash_Browns.setBounds (35, 80, 100, 25);
        pancake.setBounds (35, 50, 100, 25);
        calculate_Total.setBounds (295, 380, 125, 25);
        pancake_user.setBounds (135, 50, 100, 25);
        hashBrown_user.setBounds (135, 85, 100, 25);
    }
    
    
    
    private class CalcButtonListener implements ActionListener{
		public void actionPerformed(ActionEvent e) {
			int inputP;
			int inputHB;
			int total;
			
			inputP=Integer.parseInt(pancake_user.getText());
			inputHB=Integer.parseInt(hashBrown_user.getText());
			total=inputP+inputHB;
			
			JOptionPane.showMessageDialog(null, total);
		}
    }

    public static void main (String[] args) {
        JFrame frame = new JFrame ("test2");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Test());
        frame.pack();
        frame.setVisible (true);
    }
}
